version: '2.1'

services:
  service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/feature-toggle-api
    container_name: feature-toggle-api
    environment:
      - APPINSIGHTS_INSTRUMENTATIONKEY
      - FLYWAY_ENABLED=false
      - FEATURES_DB_HOST=feature-toggle-database
      - FEATURES_DB_PORT
      - FEATURES_DB_NAME
      - FEATURES_DB_CONN_OPTIONS
      - FEATURES_DB_USER_NAME
      - FEATURES_DB_PASSWORD
      # test users
      - TEST_ADMIN_USERNAME=admin@example.com
      - TEST_ADMIN_PASSWORD=Password12
      - TEST_EDITOR_USERNAME=editor@example.com
      - TEST_EDITOR_PASSWORD=Password12
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - $SERVER_PORT:$SERVER_PORT
  database:
    build:
      context: docker/database
    image: hmcts/feature-toggle-database
    container_name: feature-toggle-database
    environment:
      - FEATURES_DB_PASSWORD
    ports:
      - 5429:5432
