server:
  port: 8580
  servlet:
      session:
        timeout: ${SERVER_SESSION_TIMEOUT:1800}

management:
  endpoints:
    web:
      base-path: /

flyway:
  schemas: public

info:
   app:
      name: Feature Toggle API
      description: This application allows to enable/disable features at runtime without deployment.

spring:
  application:
    name: Feature Toggle API
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${FEATURES_DB_HOST:localhost}:${FEATURES_DB_PORT:5432}/${FEATURES_DB_NAME:features}${FEATURES_DB_CONN_OPTIONS:}
    username: ${FEATURES_DB_USER_NAME:featuretoggler}
    password: ${FEATURES_DB_PASSWORD:}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: FeatureToggleHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  session:
    store-type: jdbc

users:
  admins:
    - username: ${TEST_ADMIN_USERNAME}
      password: ${TEST_ADMIN_PASSWORD}
    - username: ${CMC_ADMIN_USERNAME}
      password: ${CMC_ADMIN_PASSWORD}
    - username: ${PROBATE_ADMIN_USERNAME}
      password: ${PROBATE_ADMIN_PASSWORD}

  editors:
    - username: ${TEST_EDITOR_USERNAME}
      password: ${TEST_EDITOR_PASSWORD}
    - username: ${CMC_EDITOR_USERNAME}
      password: ${CMC_EDITOR_PASSWORD}
    - username: ${PROBATE_EDITOR_USERNAME}
      password: ${PROBATE_EDITOR_PASSWORD}
