apiVersion: v1
description: A Helm chart for the feature-toggle-api (https://github.com/hmcts/feature-toggle-api)
name: rpe-feature-toggle-api
version: 0.0.2
icon: https://github.com/hmcts/rpe-feature-toggle-api/raw/master/charts/rpe-feature-toggle-api/images/icons8-java-50.png
keywords:
  - feature-toggle-api
