memoryRequests: '512Mi'
cpuRequests: '100m'
memoryLimits: '1024Mi'
cpuLimits: '2500m'
readinessPath: '/health'
readinessDelay: 30
readinessTimeout: 3
readinessPeriod: 15
livenessPath: '/health/liveness'
livenessDelay: 30
livenessTimeout: 3
livenessPeriod: 15
livenessFailureThreshold: 3

importer:
  kvSecretRef: kvcreds
  cron:
    enabled: false
    schedule: '*/5 * * * *'
    concurrencyPolicy: Forbid
    image: hmcts.azurecr.io/hmcts/feature-toggle-importer:db1fs8  # pin to specific tag
    command: echo FEATURE_TOGGLE_API_URL=${FEATURE_TOGGLE_API_URL}
    imagePullPolicy: Always
  oneoff:
    enabled: false
    image: hmcts.azurecr.io/hmcts/feature-toggle-importer:db1fs8  # pin to specific tag
    command: echo FEATURE_TOGGLE_API_URL=${FEATURE_TOGGLE_API_URL}
    imagePullPolicy: Always

postgresql:
  enabled: true

java:
  image: hmcts.azurecr.io/hmcts/rpe-feature-toggle-api:latest
  applicationPort: 8580
  registerAdditionalDns:
    enabled: false
  postgresql:
    postgresqlDatabase: hmcts
    postgresqlUsername: hmcts
    postgresqlPassword: hmcts
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
    persistence:
      enabled: false
  environment:
    FLYWAY_ENABLED: true
    FLYWAY_NOOP_STRATEGY: false
    FEATURES_DB_HOST: "{{ .Release.Name }}-postgresql"
    FEATURES_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    FEATURES_DB_USER_NAME: "{{ .Values.postgresql.postgresqlUsername}}"
    FEATURES_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    LOGBACK_REQUIRE_THREAD: false
    LOGBACK_REQUIRE_ALERT_LEVEL: false
    LOGBACK_REQUIRE_ERROR_CODE: false
  keyVaults:
    "rpe-ft-api":
      resourceGroup: rpe-feature-toggle-api
      secrets:
        - admin-username-cmc
        - admin-password-cmc
        - editor-username-cmc
        - editor-password-cmc
        - admin-username-divorce
        - admin-password-divorce
        - editor-password-divorce
        - editor-username-divorce
        - admin-password-probate
        - admin-username-probate
        - editor-password-probate
        - editor-username-probate
        - admin-password-test
        - admin-username-test
        - editor-password-test
        - editor-username-test
