{{- if .Values.importer.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "hmcts.releaseName" . }}-importer
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "hmcts.releaseName" . }}-importer
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ template "hmcts.releaseName" . }}
spec:
  schedule: {{ .Values.importer.schedule | quote }}
  concurrencyPolicy: {{ .Values.importer.concurrencyPolicy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hmcts.releaseName" . }}-importer
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ template "hmcts.releaseName" . }}-importer
        spec:
          initContainers:
          - name: {{ template "hmcts.releaseName" . }}-importer-init
            image: busybox
            command: ['sh', '-c', 'for i in $(seq 1 300); do nc -zvw1 {{ template "hmcts.releaseName" . }} 80 && exit 0 || sleep 3; done; exit 1']
          containers:
          - image: {{ .Values.importer.image }}
            name: {{ template "hmcts.releaseName" . }}-importer
            imagePullPolicy: {{ .Values.importer.imagePullPolicy }}
            command: ['sh', '-c', '{{ .Values.importer.command }}']
          env:
            - name: FEATURE_TOGGLE_API_URL
              value: 'http://{{ template "hmcts.releaseName" . }}/api/ff4j/store/features/'
            - name: VERBOSE
              value: 'true'
          restartPolicy: Never
      backoffLimit: 4
{{- end }}